os:
  - linux
sudo: required
language: node_js
node_js:
  - "10.0.0"

cache:
  directories:
    - node_modules

branches:
  only:
    - master
    - develop

before_script:
  - npm install codecov -g
  - npm install -g codeclimate-test-reporter
  - npm install

script:
  - npm run test-coverage
  - npm run build

after_success:
  - codecov
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && CODECLIMATE_API_HOST=$CODECLIMATE_API_HOST CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN_MASTER codeclimate-test-reporter < coverage/lcov.info
  - test $TRAVIS_BRANCH = "develop" && test $TRAVIS_PULL_REQUEST = "false" && CODECLIMATE_API_HOST=$CODECLIMATE_API_HOST CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN_DEVELOP codeclimate-test-reporter < coverage/lcov.info

notifications:
  email:
    on_failure: change
    on_success: change
  slack: quantified-self-io:gWxqdRGo14eo9MoBMtIPX6ME

deploy:
  provider: npm
  email: jimmykane9@gmail.com
  skip_cleanup: true
  api_key:
    secure: tFGNe8sSJVqFS+mwARHWznj9BnDkVFEabPyXc5x4R7UP1yHmRsk/o8WDN/dGfoRm+bJ7bzkhJTKb9WAjTIQjcG6Yjl6bRnpm48NQhlr2yKqBZ/mgQ1jO4/WSksNvk/pW1cIjymvhpyrN8bV6LgQdqz4LCq458VJGyDOAVuhWdltNxk91+c7PeAavxOXzYHGmyHM1nxZiG797f59qDne88YGDiNloP4vGtSCeNaZJntdOFt1fJMMnfqRCjoWoO/62W2AwJnVb7NQDcpj5P4bu/+P1pWONJZxYSUYIf36EOuLPsstixdQyG6OaOFrB27RtHdj1aVtlZgxvpAXA3xIu+EcTc6oCc5/OJ9IGGvfhjTajt1bqHnIYL9h9UDB+aQK7VX0bu31kzsZkEE2PCtbL4DvkmpmNF8bXgyngxgseOgb4BXKP4jDNBO0KQ+oXSsHetA59RNUKRKoVX0F3T+yDBUGms8mw+sx+TJU/uRkYHWfMPUBitzf4XaX4Jx/sDyHHUZDw8cU7mhPnfO7hzZwj6TnPaOodL4Jn0grj2bnyso6YQUaDldKsVuSJCNB7yNhv9PJXwLJ2T4QtAIpcBvDyCa9O1cTFV2Q1brWft03PI8oyx0WdkiM9HoHXkVehHqQbANtVDe2ntcQW4r4hbtSPLWuSC7Sa/yOhF5gTCSKcnvM=
  on:
    branch: master
    repo: jimmykane/sports-lib
